options:
  hostname:
    default:
    type: string
    description: Hostname or IP of the VyOS
  user:
    type: string
    default: vyos
    description: Username for VyOS
  pass:
    type: string
    default:
    description: Password for VyOS
